package com.francisco.library_management.application.ports.libraryUser;

public interface LibraryUserRepository extends AllLibraryUsersRepository, LibraryUserByCriteriaRepository, CreateLibraryUserRepository, UpdateLibraryUserRepository, DeleteLibraryUserRepository {

}
